using MyApi.Application.Dtos.RequestDtos;
using MyApi.Application.Dtos.ResponseDtos;
using MyApi.Application.IRepositories;
using MyApi.Application.Services.Interfaces;
using MyApi.Domain.Entities;
using MyApi.Domain.Enums;

namespace MyApi.Application.Services.Implementations
{
    public class EventService : IEventService
    {
        private readonly IEventRepository _eventRepository;

        public EventService(IEventRepository eventRepository)
        {
            _eventRepository = eventRepository;
        }

        // =========================================================
        // US-BE-001
        // Get Upcoming Events
        // =========================================================

        public async Task<List<EventDto>> GetUpcomingEventsAsync(
            int pageNumber = 1,
            int pageSize = 10)
        {
            if (pageNumber < 1)
                pageNumber = 1;

            if (pageSize < 1)
                pageSize = 10;

            if (pageSize > 100)
                pageSize = 100;

            var events = await _eventRepository
                .GetUpcomingEventsAsync(
                    pageNumber,
                    pageSize);

            return events
                .Select(MapToEventDto)
                .ToList();
        }


        // =========================================================
        // US-BE-002
        // Search Events
        // =========================================================

        public async Task<List<EventDto>> SearchEventsAsync(
            SearchEventRequest request)
        {
            if (request == null)
                throw new ArgumentNullException(nameof(request));

            var events = await _eventRepository
                .SearchEventsAsync(request);

            return events
                .Select(MapToEventDto)
                .ToList();
        }


        // =========================================================
        // US-BE-003
        // Get Event By ID
        // =========================================================

        public async Task<EventDetailsDto> GetEventByIdAsync(
            Guid eventId)
        {
            if (eventId == Guid.Empty)
                throw new ArgumentException(
                    "Event ID is required.");

            var eventEntity = await _eventRepository
                .GetByIdAsync(eventId);

            if (eventEntity == null)
                throw new KeyNotFoundException(
                    "Event not found.");

            return MapToEventDetailsDto(eventEntity);
        }


        // =========================================================
        // US-BE-007
        // Create Event
        // =========================================================

        public async Task<EventDto> CreateEventAsync(
            CreateEventRequest request,
            Guid organizerId)
        {
            if (request == null)
                throw new ArgumentNullException(nameof(request));

            if (organizerId == Guid.Empty)
                throw new ArgumentException(
                    "Organizer ID is required.");

            if (string.IsNullOrWhiteSpace(request.EventName))
                throw new ArgumentException(
                    "Event name is required.");

            if (string.IsNullOrWhiteSpace(request.Eventvenue))
                throw new ArgumentException(
                    "Event venue is required.");

            if (request.EventDate <= DateTime.UtcNow)
                throw new ArgumentException(
                    "Event date must be in the future.");

            var newEvent = new Event
            {
                // Id is automatically generated by BaseEntity
                OrganizerId = organizerId,

                EventName = request.EventName,

                EventDescription = request.EventDescription,

                Eventvenue = request.Eventvenue,

                EventDate = request.EventDate,

                EventStatus = EventStatus.Draft,

                CreatedDate = DateTime.UtcNow,

                CreatedBy = organizerId.ToString(),

                Price = request.Price,

                Image = request.Image
            };

            await _eventRepository.AddAsync(newEvent);

            await _eventRepository.SaveChangesAsync();

            return MapToEventDto(newEvent);
        }


        // =========================================================
        // Update Event
        // Organizer can update their own event
        // =========================================================

        public async Task<bool> UpdateEventAsync(
            Guid eventId,
            UpdateEventRequest request,
            Guid organizerId)
        {
            if (eventId == Guid.Empty)
                throw new ArgumentException(
                    "Event ID is required.");

            if (request == null)
                throw new ArgumentNullException(nameof(request));

            if (organizerId == Guid.Empty)
                throw new ArgumentException(
                    "Organizer ID is required.");

            var existingEvent = await _eventRepository
                .GetByIdAsync(eventId);

            if (existingEvent == null)
                throw new KeyNotFoundException(
                    "Event not found.");

            // Ensure the organizer owns the event
            if (existingEvent.OrganizerId != organizerId)
                throw new UnauthorizedAccessException(
                    "You are not authorized to update this event.");

            // Cancelled events cannot be updated
            if (existingEvent.EventStatus == EventStatus.Cancelled)
                throw new InvalidOperationException(
                    "A cancelled event cannot be updated.");

            if (!string.IsNullOrWhiteSpace(request.EventName))
            {
                existingEvent.EventName =
                    request.EventName;
            }

            if (request.EventDescription != null)
            {
                existingEvent.EventDescription =
                    request.EventDescription;
            }

            if (!string.IsNullOrWhiteSpace(request.Eventvenue))
            {
                existingEvent.Eventvenue =
                    request.Eventvenue;
            }

            if (request.EventDate.HasValue)
            {
                if (request.EventDate.Value <= DateTime.UtcNow)
                    throw new ArgumentException(
                        "Event date must be in the future.");

                existingEvent.EventDate =
                    request.EventDate.Value;
            }

            // Update audit information
            existingEvent.UpdatedDate = DateTime.UtcNow;
            existingEvent.UpdatedBy = organizerId.ToString();

            await _eventRepository.SaveChangesAsync();

            return true;
        }


        // =========================================================
        // Cancel Event
        // Organizer can cancel their own event
        // =========================================================

        public async Task<bool> CancelEventAsync(
            Guid eventId,
            Guid organizerId)
        {
            if (eventId == Guid.Empty)
                throw new ArgumentException(
                    "Event ID is required.");

            if (organizerId == Guid.Empty)
                throw new ArgumentException(
                    "Organizer ID is required.");

            var existingEvent = await _eventRepository
                .GetByIdAsync(eventId);

            if (existingEvent == null)
                throw new KeyNotFoundException(
                    "Event not found.");

            // Ensure organizer owns the event
            if (existingEvent.OrganizerId != organizerId)
                throw new UnauthorizedAccessException(
                    "You are not authorized to cancel this event.");

            // Already cancelled
            if (existingEvent.EventStatus == EventStatus.Cancelled)
                return true;

            existingEvent.EventStatus =
                EventStatus.Cancelled;

            // Update audit information
            existingEvent.UpdatedDate = DateTime.UtcNow;
            existingEvent.UpdatedBy = organizerId.ToString();

            await _eventRepository.SaveChangesAsync();

            return true;
        }


        // =========================================================
        // Mapping
        // Entity -> EventDto
        // =========================================================

        private static EventDto MapToEventDto(Event eventEntity)
        {
            return new EventDto
            {
                EventId = eventEntity.Id,
                OrganizerId = eventEntity.OrganizerId,
                EventName = eventEntity.EventName,
                EventDescription = eventEntity.EventDescription,
                Eventvenue = eventEntity.Eventvenue,
                EventDate = eventEntity.EventDate,
                EventStatus = eventEntity.EventStatus,
                Price = eventEntity.Price,
                Image = eventEntity.Image
            };
        }


        // =========================================================
        // Mapping
        // Entity -> EventDetailsDto
        // =========================================================

        private static EventDetailsDto MapToEventDetailsDto(
    Event eventEntity)
        {
            return new EventDetailsDto
            {
                EventId = eventEntity.Id,
                OrganizerId = eventEntity.OrganizerId,
                EventName = eventEntity.EventName,
                EventDescription = eventEntity.EventDescription,
                Eventvenue = eventEntity.Eventvenue,
                EventDate = eventEntity.EventDate,
                EventStatus = eventEntity.EventStatus,
                Price = eventEntity.Price,
                Image = eventEntity.Image,
            };
        }
    }
}